import json
import os
from pathlib import Path
import shutil

class DockerfileGenerator:
    def __init__(self, registry_path):
        with open(registry_path, 'r') as f:
            self.registry = json.load(f)

    def resolve_dependencies(self, selected_ids):
        resolved = []
        visited = set()

        def visit(comp_id):
            if comp_id in visited:
                return
            if comp_id not in self.registry:
                return
            
            for dep in self.registry[comp_id].get("dependencies", []):
                visit(dep)
            
            visited.add(comp_id)
            resolved.append(comp_id)

        if "ubuntu-base" in self.registry:
            visit("ubuntu-base")

        for comp_id in selected_ids:
            visit(comp_id)
        
        return resolved

    def _get_package_list(self, packages_data):
        pkgs = []
        if isinstance(packages_data, list):
            pkgs = packages_data
        elif isinstance(packages_data, dict):
            pkgs = packages_data.get("preset", [])
            custom = packages_data.get("custom", "").strip()
            if custom:
                pkgs.extend([p.strip() for p in custom.replace(",", " ").split() if p.strip()])
        return sorted(list(set(pkgs)))

    def _generate_pyproject_toml(self, packages, output_path):
        pkg_metadata = {}
        if "python" in self.registry:
            for opt in self.registry["python"].get("sub_selection", {}).get("options", []):
                if opt.get("url"):
                    pkg_metadata[opt["name"]] = opt["url"]

        content = [
            "[project]",
            "name = \"fair-data-machine-custom\"",
            "version = \"0.1.0\"",
            "dependencies = ["
        ]
        
        for pkg in self._get_package_list(packages):
            url = pkg_metadata.get(pkg)
            if url:
                entry = f"{pkg} @ {url}"
            else:
                entry = pkg
            content.append(f"  \"{entry}\",")
            
        content.append("]")
        
        with open(output_path / "pyproject.toml", "w") as f:
            f.write("\n".join(content))

    def _generate_r_packages_txt(self, packages, output_path):
        content = [
            "# Custom R package manifest",
            "# One package name per line.",
            ""
        ]
        for pkg in self._get_package_list(packages):
            content.append(pkg)
            
        with open(output_path / "r-packages.txt", "w") as f:
            f.write("\n".join(content))

    def _generate_node_packages_txt(self, packages, output_path):
        final_pkgs = self._get_package_list(packages)
        with open(output_path / "node_packages.txt", "w") as f:
            f.write("\n".join(final_pkgs))

    def _generate_readme(self, resolved_ids, package_selection, output_path):
        content = [
            "# Custom FAIR Data Machine Build",
            "",
            "This build package was generated by the FAIR Data Machine Builder.",
            "",
            "> [!TIP]",
            "> This directory (`custom-build/`) is overwritten every time you click \"Generate Build Package\" in the UI.",
            "> To retain this specific configuration, **copy or rename** this directory (e.g., to `my-project-build/`) before generating a new one.",
            "",
            "## Machine Profile",
            "The following components are included in this workstation:",
            ""
        ]
        
        for comp_id in resolved_ids:
            comp = self.registry[comp_id]
            name = comp['name']
            url = comp.get('url')
            
            if url:
                line = f"- **[{name}]({url})**"
            else:
                line = f"- **{name}**"
                
            if comp_id in package_selection:
                pkgs = self._get_package_list(package_selection[comp_id])
                if pkgs:
                    line += f": {', '.join(pkgs)}"
            content.append(line)
            
        content.extend([
            "",
            "## Build & Test",
            "To build the machine and verify the installation:",
            "```bash",
            "# 1. Build the image",
            "docker build -t my-custom-machine .",
            "",
            "# 2. Run smoke tests",
            "./test-image.sh my-custom-machine",
            "```"
        ])

        persistence_rows = [
            "| **Workspace** | `/home/dartfx/workspace` | Your project files and data |"
        ]
        
        for comp_id in resolved_ids:
            comp = self.registry.get(comp_id, {})
            for vol in comp.get("persistence_volumes", []):
                persistence_rows.append(f"| **{comp.get('name', comp_id)}** | `{vol['path']}` | {vol['description']} |")

        content.extend([
            "",
            "## Quick Start",
            "",
            "### 1. Interactive Shell",
            "To launch the machine and enter an interactive shell as the `dartfx` user with your current directory mapped as a workspace:",
            "```bash",
            "docker run --rm -it \\",
            "  -v \"$(pwd)\":/home/dartfx/workspace \\",
            "  -w /home/dartfx/workspace \\",
            "  my-custom-machine \\",
            "  su - dartfx",
            "```",
            "",
            "### 2. Persistence",
            "To persist data across container restarts (e.g., databases and models), map volumes for these paths:",
            "",
            "| Component | Container Path | Description |",
            "| --- | --- | --- |"
        ])
        content.extend(persistence_rows)
        content.extend([
            "",
            "Example with persistence:",
            "```bash",
            "docker run --rm -it \\",
            "  -v \"$(pwd)\":/home/dartfx/workspace \\",
            "  -v \"pgdata\":/var/lib/postgresql/data \\",
            "  -v \"ollama_models\":/usr/share/ollama/.ollama \\",
            "  my-custom-machine \\",
            "  su - dartfx",
            "```"
        ])
        
        with open(output_path / "README.md", "w") as f:
            f.write("\n".join(content))

    def _generate_smoke_test(self, resolved_ids, package_selection, output_path):
        content = [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            "",
            "# Safety check: ensure we are inside a container",
            "if [ ! -f /.dockerenv ]; then",
            "  echo \"[error] smoke-test.sh must be run INSIDE the Docker container.\"",
            "  echo \"Please use: ./test-image.sh <image_name>\"",
            "  exit 1",
            "fi",
            "",
            "echo \"[test] Starting smoke tests...\"",
            "",
            "check_cmd() {",
            "  local name=\"$1\"",
            "  command -v \"$name\" >/dev/null",
            "  echo \"[ok] command available: $name\"",
            "}",
            "",
            "check_file() {",
            "    if [ -f \"$1\" ]; then",
            "        echo \"[ok] file exists: $1\"",
            "    else",
            "        echo \"[error] file missing: $1\"",
            "        exit 1",
            "    fi",
            "}",
            ""
        ]

        # Add Component Specific Tests
        for comp_id in resolved_ids:
            comp = self.registry.get(comp_id, {})
            test_meta = comp.get("test")
            if test_meta:
                content.append(f"# Tests for {comp_id}")
                for cmd in test_meta.get("commands", []):
                    content.append(f"{cmd}")
                for file_path in test_meta.get("files", []):
                    content.append(f"check_file \"{file_path}\"")
                content.append("")

        # Add Sub-selection (Package) Tests
        for comp_id, pkgs_data in package_selection.items():
            comp = self.registry.get(comp_id)
            if not comp or "sub_selection" not in comp:
                continue
            
            pkgs = self._get_package_list(pkgs_data)
            if not pkgs:
                continue

            # Check individual option tests if any (e.g. pgvector)
            for opt in comp["sub_selection"]["options"]:
                if opt["name"] in pkgs and "test" in opt:
                    content.append(f"# Sub-option test: {opt['name']}")
                    for cmd in opt["test"].get("commands", []):
                        content.append(f"{cmd}")
                    content.append("")

            # Bulk package imports for Python
            if comp_id == "python":
                content.append("# Python library imports")
                content.append("/home/dartfx/.venvs/dartfx/bin/python - <<'PY'")
                content.append("import sys, importlib")
                content.append("failed = False")
                
                # Build import map from comp
                import_mapping = {}
                for opt in comp.get("sub_selection", {}).get("options", []):
                    if opt.get("selected", True) and "import_as" in opt:
                        import_mapping[opt["name"]] = opt["import_as"]
                
                content.append(f"import_map = {json.dumps(import_mapping)}")
                
                # Sanitize package names
                clean_pkgs = [p.split(" ")[0].split("@")[0].split("[")[0] for p in pkgs]
                
                for pkg in clean_pkgs:
                    content.append(f"pkg_name = '{pkg}'")
                    content.append("import_name = import_map.get(pkg_name, pkg_name.replace('-', '_'))")
                    content.append("try:")
                    content.append("    importlib.import_module(import_name)")
                    content.append("    print(f'[ok] python import: {pkg_name} (as {import_name})')")
                    content.append("except ImportError as e:")
                    content.append("    print(f'[error] failed to import {pkg_name}: {e}')")
                    content.append("    failed = True")
                
                content.append("if failed: sys.exit(1)")
                content.append("PY")
                content.append("")

            # Bulk package check for Node
            if comp_id == "node":
                content.append("# Node.js package check")
                for pkg in pkgs:
                    content.append(f"su - dartfx -c 'export NVM_DIR=\"$HOME/.nvm\"; source \"$NVM_DIR/nvm.sh\"; export PNPM_HOME=\"$HOME/.local/share/pnpm\"; export PATH=\"$PNPM_HOME:$PATH\"; pnpm list -g {pkg} > /dev/null' && echo '[ok] node package: {pkg}' || echo '[error] missing node package: {pkg}'")
                content.append("")

            # Bulk package check for R
            if comp_id == "r":
                content.append("# R library installation check")
                pkg_list = " ".join([f'"{p}"' for p in pkgs])
                content.append(f"Rscript -e 'pkgs <- c({pkg_list.replace(' ', ', ')}); missing <- pkgs[!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]; if(length(missing) > 0) {{ stop(\"Missing R packages: \", paste(missing, collapse=\", \")) }} else {{ cat(\"[ok] all R packages found\\n\") }}'")
                content.append("")

        content.append("echo \"[ok] All smoke tests passed!\"")
        
        test_file = output_path / "smoke-test.sh"
        with open(test_file, "w") as f:
            f.write("\n".join(content))
        test_file.chmod(0o755)

        # Also copy the host-side runner
        runner_content = [
            "#!/usr/bin/env bash",
            "# Runner to execute smoke tests against a built image",
            "set -euo pipefail",
            "",
            "IMAGE=\"${1:-}\"",
            "if [[ -z \"$IMAGE\" ]]; then",
            "  echo \"Usage: $0 <image-name>\"",
            "  exit 1",
            "fi",
            "",
            "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"",
            "",
            "echo \"[test] Running smoke tests for: $IMAGE\"",
            "docker run --rm \\",
            "  -v \"$SCRIPT_DIR/smoke-test.sh\":/tmp/smoke-test.sh:ro \\",
            "  \"$IMAGE\" \\",
            "  bash /tmp/smoke-test.sh",
            ""
        ]
        runner_file = output_path / "test-image.sh"
        with open(runner_file, "w") as f:
            f.write("\n".join(runner_content))
        runner_file.chmod(0o755)

    def generate(self, selected_ids, package_selection, output_dir):
        resolved_ids = self.resolve_dependencies(selected_ids)
        output_path = Path(output_dir)
        if output_path.exists():
            shutil.rmtree(output_path)
        output_path.mkdir(parents=True)

        system_packages = set()
        env_vars = {}
        install_steps = []

        for comp_id in resolved_ids:
            comp = self.registry[comp_id]
            system_packages.update(comp.get("system_packages", []))
            env_vars.update(comp.get("env", {}))
            
            # Aggregate standard install steps
            steps = comp.get("install", [])[:]
            
            # Handle sub-selection logic (extensions/packages)
            if "sub_selection" in comp and comp_id in package_selection:
                selected_names = package_selection[comp_id]
                for opt in comp["sub_selection"]["options"]:
                    if opt["name"] in selected_names:
                        # Append sub-option system packages
                        system_packages.update(opt.get("system_packages", []))
                        # Append sub-option install steps
                        steps.extend(opt.get("install", []))

            if steps:
                install_steps.append((comp_id, steps))

            # Handle manifest generation if packages are selected
            if comp_id == "python" and "python" in package_selection:
                self._generate_pyproject_toml(package_selection["python"], output_path)
            elif comp_id == "r" and "r" in package_selection:
                self._generate_r_packages_txt(package_selection["r"], output_path)
            elif comp_id == "node" and "node" in package_selection:
                self._generate_node_packages_txt(package_selection["node"], output_path)

        # Generate Documentation
        self._generate_readme(resolved_ids, package_selection, output_path)
        
        # Generate Smoke Test
        self._generate_smoke_test(resolved_ids, package_selection, output_path)

        # Copy static config files
        root_dir = Path(__file__).parent.parent.parent
        supervisord_src = root_dir / "supervisord.conf"
        if supervisord_src.exists():
            shutil.copy(supervisord_src, output_path / "supervisord.conf")

        dockerfile = [
            "# Optimized FAIR Data Machine Build",
            "FROM ubuntu:24.04",
            "ARG DEBIAN_FRONTEND=noninteractive",
            "SHELL [\"/bin/bash\", \"-o\", \"pipefail\", \"-c\"]",
            "",
            "# Suppress service starts during build",
            "RUN printf '#!/bin/sh\\nexit 101' > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d",
            ""
        ]
        
        if system_packages:
            pkg_list = sorted(list(system_packages))
            dockerfile.append("# System Dependencies")
            dockerfile.append("RUN apt-get update && \\")
            dockerfile.append("    apt-get install -y -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confold\" \\")
            dockerfile.append("    --no-install-recommends --no-install-suggests \\")
            for i, pkg in enumerate(pkg_list):
                dockerfile.append(f"      {pkg} \\")
            dockerfile.append("    && rm -rf /var/lib/apt/lists/* /usr/sbin/policy-rc.d")
            dockerfile.append("")

        # Add COPY instruction for supervisord (Moved after apt-get install to avoid conffile conflict)
        if (output_path / "supervisord.conf").exists():
            dockerfile.append("# Process Manager Configuration")
            dockerfile.append("COPY supervisord.conf /etc/supervisor/supervisord.conf")
            dockerfile.append("")

        if env_vars:
            dockerfile.append("# Environment Variables")
            for k, v in env_vars.items():
                dockerfile.append(f"ENV {k}=\"{v}\"")
            dockerfile.append("")

        for comp_id, steps in install_steps:
            dockerfile.append(f"# Component: {comp_id}")
            
            for step in steps:
                dockerfile.append(f"RUN {step}")

            # Special case: copy manifests and setup venv if language selected (run AFTER install steps so uv is present)
            if comp_id == "python" and (output_path / "pyproject.toml").exists():
                dockerfile.append("# Python: Install packages into venv")
                dockerfile.append("COPY pyproject.toml /opt/dartfx/pyproject.toml")
                dockerfile.append("RUN mkdir -p /home/dartfx/.venvs && chown dartfx:dartfx /home/dartfx/.venvs")
                dockerfile.append("RUN su - dartfx -c '/usr/local/bin/uv venv /home/dartfx/.venvs/dartfx'")
                dockerfile.append("RUN su - dartfx -c '/usr/local/bin/uv pip install -r /opt/dartfx/pyproject.toml --python /home/dartfx/.venvs/dartfx/bin/python'")
            
            if comp_id == "r" and (output_path / "r-packages.txt").exists():
                dockerfile.append("# R: Install packages")
                dockerfile.append("COPY r-packages.txt /opt/dartfx/r-packages.txt")
                dockerfile.append("RUN Rscript -e 'pkgs <- readLines(\"/opt/dartfx/r-packages.txt\"); install.packages(pkgs, repos=\"https://cloud.r-project.org\")'")

            if comp_id == "node" and (output_path / "node_packages.txt").exists():
                # Check if file is empty to avoid pnpm add -g errors
                with open(output_path / "node_packages.txt", "r") as f:
                    pkgs_content = f.read().strip()
                
                if pkgs_content:
                    dockerfile.append("# Node: Install global packages")
                    dockerfile.append("COPY node_packages.txt /opt/dartfx/node_packages.txt")
                    dockerfile.append("RUN su - dartfx -c 'export NVM_DIR=\"$HOME/.nvm\"; source \"$NVM_DIR/nvm.sh\"; export PNPM_HOME=\"$HOME/.local/share/pnpm\"; export PATH=\"$PNPM_HOME:$PATH\"; pnpm setup; xargs pnpm add -g < /opt/dartfx/node_packages.txt'")
            
            dockerfile.append("")

        dockerfile.append("WORKDIR /home/dartfx/workspace")
        dockerfile.append("CMD [\"/usr/bin/supervisord\", \"-n\", \"-c\", \"/etc/supervisor/supervisord.conf\"]")

        with open(output_path / "Dockerfile", "w") as f:
            f.write("\n".join(dockerfile))
        
        return str(output_path)

if __name__ == "__main__":
    import sys
    registry = "config/components.json"
    gen = DockerfileGenerator(registry)
    selection = ["python", "postgres"]
    pkgs = {"python": ["pandas", "duckdb"]}
    result = gen.generate(selection, pkgs, "custom-build")
    print(f"Build package generated at {result}")
